### ISSUE TITLE
Some optimizations

### ISSUE THREAD

**Issue by CyanoFresh** [waylaidwanderer/PHP-SteamCommunity#46] opened 2016-07-13 13:44 UTC
Hello. @waylaidwanderer if you see this post - please reply. I need to know if this project is active. 
If so - please do some optimizations - requests are so slow (#41) or explain how does the code work (some examples)

**Comment by waylaidwanderer** [comment] 2016-07-13 21:16
Pretty busy lately, but feel free to contribute with pull requests. The code is pretty self-explanatory. Documentation will come later when the project reaches a point I can consider "v1.0".

Duplicate of #41

**Closed as completed by waylaidwanderer** 2016-07-13 21:16 UTC
